name: gastronomic_os
description: A new Flutter project for Household Gastronomic OS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shadcn_ui: ^0.8.0
  flutter_animate: ^4.5.0
  responsive_framework: ^1.4.0
  skeletonizer: ^1.4.1
  uuid: ^4.5.1
  inflection3: ^0.5.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - Documentation/test_recipes/json/
