name: gastronomic_os
description: A new Flutter project for Household Gastronomic OS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  supabase_flutter: ^2.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shadcn_ui: ^0.8.0
  flutter_animate: ^4.5.0
  responsive_framework: ^1.4.0
  skeletonizer: ^1.4.1
  uuid: ^4.5.2
  inflection3: ^0.5.3+2
  dotenv: ^4.2.0
  shared_preferences: ^2.5.4
  logger: ^2.6.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - Documentation/test_recipes/json/
